# Generated by Django 5.2.5 on 2026-02-08 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_vote_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'position')},
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.CharField(max_length=10),
        ),
    ]
