# Generated by Django 5.2.5 on 2026-02-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_vote_unique_together_vote_vote_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(default='General Election', max_length=200)),
                ('is_active', models.BooleanField(default=False, help_text='Current active status')),
                ('is_manual_override', models.BooleanField(default=False, help_text='Check to use manual controls instead of schedule')),
                ('scheduled_start', models.DateTimeField(blank=True, help_text='When voting should automatically start', null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, help_text='When voting should automatically end', null=True)),
                ('manual_start_time', models.DateTimeField(blank=True, help_text='When election was manually started', null=True)),
                ('manual_end_time', models.DateTimeField(blank=True, help_text='When election was manually ended', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Election Settings',
            },
        ),
    ]
